version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    #The project contains .env file
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres
    environment:
    #these are the database credentials on my local machine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ramu
      - POSTGRES_DB=tutorsystemdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
